### ISSUE TITLE
Unable to run this code

### ISSUE THREAD

**Issue by Nestor12-dev** [kgsensei/Quizizz-Bot-Flood#3]
Can you please just tell me how to run it. I don't know because you haven't given any info. Is there anything to do after copying this code and running it as .py file. Please do write a complete guide for it as this is the only working one present.....HELP!!!Please

**Comment by Nestor12-dev** [comment]
And please also tell what all programs/drivers we need like selenium,etc

**Comment by kgsensei** [comment]
Sorry for not adding a readme file. I was too busy at the time of creating this code. Can you please give me some information on the device you are using and what browser you would like to use for the bot?

**Comment by Nestor12-dev** [comment]
I am using a windows place and i would like to use chrome browser

**Comment by Nestor12-dev** [comment]
And what about 8the and 23re line.....is there any change for chrome users and can i run the script directly from visual studio code

**Comment by kgsensei** [comment]
No change needs to be made to lines 8 or 23.

The web driver for chrome can be found here:
[Chrome WebDriver Download](https://sites.google.com/a/chromium.org/chromedriver/downloads)
Make sure you get the driver matching your currently installed chrome.

After you download the web driver for chrome you need to edit this line to include the exe name:
```
webdriver_location="<exe_file_name/path_here>"
```

If you are using chrome instead of edge you also need to change the following lines from:
```
options=EdgeOptions()
options.use_chromium=True
options.binary_location=r'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
browser=Edge(options=options,executable_path=webdriver_location)
```
To:
```
options=webdriver.ChromeOptions()
options.use_chromium=True
options.binary_location=r'C:\Program Files\Google\Chrome\Application\chrome.exe'
browser=webdriver.Chrome(options=options,executable_path=webdriver_location)
```
